[project]
name = "elf"
version = "0.1.0"
description = "A festive helper package for Advent of Code."
authors = [{ name = "Caleb", email = "caleb@typeerror.com" }]
license = "MIT"
dependencies = ["requests"]

[project.scripts]
elf = "elf.cli.main:main"
